version: '3.1'

services:
  browserless:
    image: browserless/chrome:latest
    container_name: browserless
    restart: always
    volumes:
      - /Users/dcf/projects/docker-services/pg-volume:/var/lib/postgresql/data
    environment:
      DEBUG: 'browserless*'
      PREBOOT_CHROME: 'true'
      MAX_CONCURRENT_SESSIONS: 10
      KEEP_ALIVE: 'true'
    ports:
      - 4000:3000